spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.9/WeChatSell?characterEncoding=utf-8&userSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
server:
  context-path: /sell
  port: 8080